### ISSUE TITLE
Is it secured for saving secret on cookies

### ISSUE THREAD

**Issue by nawa410** [FlyersWeb/angular-symfony#14]
Hi, first thanks for this wonderful angular-symfony template, i'm using it right now. 
But i'm just wondering is it safe to save hashed password in cookies?

**Comment by FlyersWeb** [comment]
Hi, actually most of 3rd party auth works by sending the password hash on the network to generate token. To have a secure communication layer you'll need an HTTPS connection so to disallow connection hijacking. Even if the attacker bypass the HTTPS it will need to know the salt in order to probably be able to crack the SHA512 encrypted 5000 times. So yes, it possible but should be really tedious even for some big corporations.
Let me know if the answer corresponds to what you asked.
Regards

**Comment by nawa410** [comment]
yes. I'm glad to hear it and sorry for this newbie question and thanks for your clear answer :)

**Comment by FlyersWeb** [comment]
There is no useless question we are all newbies at some point of our lives. I'm glad you use this bootstrap and do not hesitate to pull request new features ;)
